# Generated by Django 5.1.3 on 2024-11-16 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spartanspacepage', '0002_tasks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tasks',
            new_name='Task',
        ),
    ]
