# Generated by Django 5.1.3 on 2024-11-17 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spartanspacepage', '0003_rename_tasks_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='organization',
            field=models.CharField(choices=[('ssc', 'Alangilan SSC'), ('cursor', 'CURSOR')], default='chess_club', max_length=20),
        ),
    ]
