# Generated by Django 5.1.3 on 2024-11-17 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spartanspacepage', '0004_post_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='organization',
            field=models.CharField(choices=[('ssc', 'Alangilan SSC'), ('cursor', 'CURSOR')], default='BatStateU', max_length=20),
        ),
    ]
