# Generated by Django 5.1.3 on 2024-11-17 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spartanspacepage', '0005_alter_post_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='organization',
            field=models.CharField(choices=[('Alangilan SSC', 'SSC'), ('CURSOR', 'Computer Engineering Dept.')], default='BatStateU', max_length=20),
        ),
    ]
