# Generated by Django 5.1.3 on 2024-11-17 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spartanspacepage', '0006_alter_post_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='overview',
            field=models.TextField(default='Event Overview', max_length=1000),
            preserve_default=False,
        ),
    ]
