# Generated by Django 5.1.3 on 2024-12-17 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spartanspacepage', '0009_task_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='organization',
        ),
    ]
